apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ACGE-api
type: Opaque
data:
  mysql-root-password: cm9vdF9wYXNzd29yZA==  # Base64 de "root_password"
  mysql-database: cnJob29uZGF0YWJhc2U=      # Base64 de "restdatabase"
  mysql-user: cm9vdA==                     # Base64 de "root"
  mysql-password: cm9vdF9wYXNzd29yZA==      # Base64 de "root_password"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: LFBT-api
type: Opaque
data:
  postgres-password: cGFzc3dvcmQ=           # Base64 de "password"
  postgres-database: c29hcGRhdGFiYXNl       # Base64 de "soapdatabase"
  postgres-user: c29hcF91c2Vy               # Base64 de "soap_user"
