apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api
  namespace: ACGE-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
      - name: rest-api
        image: rest-api:1  # Simplificado para la versión 1 local
        ports:
        - containerPort: 4000
        env:
        - name: MYSQL_HOST
          value: mysql-service.acge-api.svc.cluster.local
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-database
        - name: REDIS_HOST
          value: redis.acge-api.svc.cluster.local
        - name: REDIS_PORT
          value: "6379"
        - name: SOAP_URL
          value: http://soap-service.lfbt-api.svc.cluster.local:5000
