apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ACGE-api
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ=      # Base64 de "password"
  mysql-database: cmVzdGRi               # Base64 de "restdatabase"
  mysql-user: cmVzdF91c2Vy               # Base64 de "rest_user"
  mysql-password: cmVzdHBhc3N3b3Jk       # Base64 de "restpassword"
