apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ACGE-api
type: Opaque
data:
  mysql-user: cm9vdA==             # Base64 de "root"
  mysql-password: cm9vdF9wYXNzd29yZA==  # Base64 de "root_password"
  mysql-database: cnJobg==          # Base64 de "rrhh"
