apiVersion: v1
kind: Service
metadata:
  name: rest-api-service
  namespace: ACGE-api
spec:
  type: NodePort  # Cambiar de ClusterIP a NodePort
  ports:
  - port: 4000  # Puerto dentro del clúster
    targetPort: 4000  # Puerto en el contenedor
    nodePort: 30001  # Puerto expuesto externamente (puede variar)
  selector:
    app: rest-api
