apiVersion: v1
kind: Service
metadata:
  name: soap-api-service
  namespace: team-api
spec:
  selector:
    app: soap-api
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
