apiVersion: apps/v1
kind: Deployment
metadata:
  name: soap-api
  namespace: LFBT-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soap-api
  template:
    metadata:
      labels:
        app: soap-api
    spec:
      containers:
      - name: soap-api
        image: soap-api:1  # Simplificado para la versión 1 local
        ports:
        - containerPort: 5000
        env:
        - name: POSTGRES_HOST
          value: postgres-service.lfbt-api.svc.cluster.local
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-database
        - name: REST_API_URL
          value: http://rest-api-service.acge-api.svc.cluster.local:4000
