apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: LFBT-api
type: Opaque
data:
  postgres-password: cGFzc3dvcmQ=       # Base64 de "password"
  postgres-database: c29hcGRi           # Base64 de "soapdatabase"
  postgres-user: c29hcF91c2Vy           # Base64 de "soap_user"
