apiVersion: v1
kind: Service
metadata:
  name: rest-api-service
  namespace: team-api
spec:
  selector:
    app: rest-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
